# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import Select
from urllib3.packages.six import b



class Reservoir_data():
  webURL = "https://fhy.wra.gov.tw/reservoirpage_2011/storagecapacity.aspx?fbclid=IwAR0Umtyt_LvN6dMNeH5SKTsXTB0XyTUA974FClxePe8pLD-grqizWg5Gu1Y"

  def __init__(self, reservoir_name, date):
    # some attributes
    self.reservoir_name = reservoir_name
    self.date = date
    # driver setup
    self.options = webdriver.ChromeOptions()
    self.options.add_experimental_option('excludeSwitches', ['enable-logging'])
    self.driver = webdriver.Chrome(options=self.options)

  
  def crawl(self):
    '''
    reservoir  format: "XXX水庫"
    date        format: tuple/set/list (YYYY, MM, DD), and the numbers shouldn't contain leading zero!!!!
    '''
    self.driver.get(Reservoir_data.webURL)
    self.driver.set_window_size(320,180)

    
    #select search domain: 所有水庫
    self.dropdown = Select(self.driver.find_element(By.ID, "ctl00_cphMain_cboSearch")).select_by_visible_text('所有水庫')
    time.sleep(1)

    #select year
    self.dropdown = Select(self.driver.find_element(By.ID, "ctl00_cphMain_ucDate_cboYear")).select_by_visible_text(str(self.date[0]))
    #select month
    self.dropdown = Select(self.driver.find_element(By.ID, "ctl00_cphMain_ucDate_cboMonth")).select_by_visible_text(str(self.date[1]))
    #select day
    self.dropdown = Select(self.driver.find_element(By.ID, "ctl00_cphMain_ucDate_cboDay")).select_by_visible_text(str(self.date[2]))

    #search and wait a second (literally)
    self.driver.find_element(By.ID, "ctl00_cphMain_btnQuery").click()
    time.sleep(1)

    '''印出所有水庫的資料
    self.table = self.driver.find_element_by_id('ctl00_cphMain_gvList')
    self.trlist = self.table.find_elements_by_tag_name('tr')[:-1]
    for row in self.trlist:
      self.tdlist = row.find_elements_by_tag_name('td')
      for col in self.tdlist:
        print(col.text + '\t',end='')
      print('\n')
    # 印出所有水庫的資料'''

    # '''return 個別水庫的資料
    self.table = self.driver.find_element_by_id('ctl00_cphMain_gvList')
    self.reservoir = self.table.find_element_by_xpath('//tr[contains(.,"'+ self.reservoir_name +'")]').find_elements_by_tag_name('td')
    
    self.data = []
    for col in self.reservoir: 
      self.data.append(col.text)

    self.driver.quit()
    return self.data
    # return 個別水庫的資料'''
    





a = Reservoir_data('石門水庫', (2019, 2, 27))
data_test = a.crawl()
print(data_test)